### ISSUE TITLE
Window title should show current week

### ISSUE THREAD

**Issue by ohwgiles** [ohwgiles/focal#10]
Instead of reading "focal", the window title should by default display the current week, e.g. "Week 27"

**Comment by David-Mayes** [comment]
Is it alright if I help with this? 

Also, when I try to run focal, I just get "Set main/{url,user,pass} in focal.conf", do I have to create that file? Sorry if this is a silly question, I'm new to this, and I can't find any help with it elsewhere.

**Comment by ohwgiles** [comment]
Of course, thanks for helping!

Yes, I've just added a note about that to the README. There isn't a settings UI yet so for now you need to create the config file manually.
