### ISSUE TITLE
Improve week view: Mention year(s) and month(s) of shown week 

### ISSUE THREAD

**Issue by kstenschke** [ohwgiles/focal#48]
see also: https://github.com/ohwgiles/focal/pull/46

**Comment by kstenschke** [comment]
**ohwgiles**
>  I've thought about it a couple of times but have been putting it off due to some indecision about how the month and year should be displayed near month/year boundaries. I've explained my logic in inline comments.

**ohwgiles**
> Instead of extending the title, I suggest using a subtitle https://developer.gnome.org/gtk3/stable/GtkHeaderBar.html#gtk-header-bar-set-subtitle

**ohwgiles**
> My concern with this implementation is that it treats months and years inconsi stently. You will be able to see "December/January 2018" and it won't be clear which month is in which year (if anything, I would read that as January being in 2018). I think we should either be completely precise ("December 2018/January 2019"), or consistently imprecise (choose "December 2018" or "January 2019" based on some other criteria). For example, we could consistently report the month and year of the Wednesday of the displayed week.
> 
> I don't mind too much which is chosen, but I think the second method would be simpler to implement and result in smaller, cleaner code with a reduced API, at the cost of just a little imprecision.

**ohwgiles**
> If the simpler, less precise method is chosen, this could simply become week_view_get_month, and it would return the month of (e.g.) the Wednesday of the displayed week. This API would be pleasingly consistent with *_get_week and *_get_year

**kstenschke**
> Another way could be to only display "week <no> <year>" in the title and add a setting to the user preferences, whether to 1. show the month within all day labels, or 2. Show the month only in the labels of the first shown and the first day of the next month, or 3. to not display the month within the day labels. What do you think?

**ohwgiles**
> Yes, moving the month to the day header would be another way to go. Although having user preferences is nice, at this early stage of the project I prefer to just choose one option (IMO 2. is best) and leave configurability for a future task.
> 
> The downside with this approach is that the year and month still get inconsistent treatment. You could also put the year alongside the month in the day header, but space is already tight there.
> 
> I think I prefer the subtitle in the window title approach.

**Comment by kstenschke** [comment]
Option 2 sounds best to me at the time being. Adding  a subtitle makes the application appear "heavier" in my opinion, as it also increases the title bar's height. To my impression enlarging the title bar should be done only if also using the added space for placing other options in it, like search field and/or buttons to switch among view modes (day / week / month).
BTW: I think the overall appearance would be more harmonic if the labels of weekdays (day on month and weekday abbreviation) and hours of the day would use just one font size.

**Comment by kstenschke** [comment]
To further explain why i am questioning the benefit of adding a subtitle: I am not sure whether the initial screenshot from the readme is outdated, or due to me using a different window manager, but focal at my place already is displayed with a title bar and an additional options bar under it.
<img width="793" alt="bildschirmfoto 2018-11-05 um 22 42 14" src="https://user-images.githubusercontent.com/1838456/48028591-2b003c80-e14c-11e8-8a22-ab5f6241f755.png">

**Comment by ohwgiles** [comment]
The subtitle should not take up any extra space, GtkHeaderBar already provides for it:

![subtitle](https://user-images.githubusercontent.com/1444499/48047590-2ca81f80-e1a1-11e8-8488-05c16a05e002.png)

The screenshot is not out of date, I suspect it's related to your window manager. There should be only one header. How do other applications that use GtkHeaderBar appear on your system? For example [Geary](https://wiki.gnome.org/Apps/Geary) or [gitg](https://wiki.gnome.org/Apps/Gitg/)?

**Comment by kstenschke** [comment]
I checked gitg: the same effect. After changing the window manager to Gnome, the header is displayed correctly. So i think the issue is probably neglectable.
