### ISSUE TITLE
Initially showing next week instead of current on sunday

### ISSUE THREAD

**Issue by kstenschke** [ohwgiles/focal#51]
Opening focal in "Monday-Sunday" view mode on a sunday initially displays the next week instead of the current.

**Comment by j4cobgarby** [comment]
Is this fixed yet? If not, I'd like to have a go at doing it.

**Comment by j4cobgarby** [comment]
I assume it is fixed though, since it's nearly a year old...

**Comment by ohwgiles** [comment]
Unfortunately I’ve had no time for this project in the last ~10 months (planning to get back to it soon) so I can’t tell from memory whether this was fixed or not. I would encourage you to take a look! `libfaketime` is useful for debugging issues like this

**Comment by j4cobgarby** [comment]
Alright, cool, thanks! I've been looking for something to do

**Comment by ohwgiles** [comment]
@j4cobgarby got a chance to look at this, actually there was a pending PR solving this I had forgotten about, sorry. If you're still interested, please do take a look at the other open issues, or open a new one :)

**Comment by j4cobgarby** [comment]
@ohwgiles oh no problem! I hadn't even got around to looking at it myself yet, haha
