### ISSUE TITLE
Detect light/dark theme

### ISSUE THREAD

**Issue by kstenschke** [ohwgiles/focal#63]
Focal should detect whether the system uses a dark or light theme and use suiting colors.
A possible solution might be something like https://lzone.de/blog/Detecting%20a%20Dark%20Theme%20in%20GTK

**Comment by ohwgiles** [comment]
Better than detecting whether it's dark or light would be just to use the colours from the theme directly, as long as appropriate ways to retrieve all the necessary colours can be found. I think the best way to start with this is [GtkStyleContext](https://developer.gnome.org/gtk3/stable/GtkStyleContext.html), see also https://developer.gnome.org/gtk3/stable/gtk-migrating-GtkStyleContext-css.html

For each colour we use, there should be a way to do something like
```
gtk_style_context_get (context, GTK_STATE_FLAG_NORMAL, "background-color", &color1, NULL);
```
