### ISSUE TITLE
Google calendar sync with outlook calendar

### ISSUE THREAD

**Issue by defrivm** [ohwgiles/focal#77]
Event/reminder shown in home widget (at a glance widget) only showing events from google calendar. Pls provide options to sync/select outlook calendar events.

**Comment by ohwgiles** [comment]
What is the home widget/at a glance widget? Focal does not have something like that.

**Comment by kstenschke** [comment]
Maybe whats meant are notifications?

**Comment by ohwgiles** [comment]
Closing due to lack of information
