### ISSUE TITLE
build fails due to gperf and windows-tz-map

### ISSUE THREAD

**Issue by sdx23** [ohwgiles/focal#78]
With HEAD the build as described in the README fails under Ubuntu 18.04.
One thing missing in the dependencies is the package "gperf".
But still the build fails, actually with the same message 
   
    windows-tz-map.gperf:6:28: fatal error: windows-tz-map.h: No such file or directory

as the CI https://ci.ohwg.net/jobs/focal/24

With 1ff76ed everything works fine.

**Comment by ohwgiles** [comment]
ok not fixed yet...working on it

**Comment by ohwgiles** [comment]
looks ok now

**Comment by sdx23** [comment]
HEAD does build now fine, thanks.
